// Fragenkatalog – ausschließlich aus der Word-Datei
// Pru_fungs_Frage_manuell_ausgewertet.docx
// Keine Änderungen, keine Ergänzungen, keine Interpretation.

const QUESTIONS = [
  {
    id: 1,
    type: 'multi',
    topic: 'Staatsrecht – Staatsstrukturprinzipien',
    q: 'Welches ist KEIN Staatsstrukturprinzip?',
    options: [
      'Demokratieprinzip',
      'Republikprinzip',
      'Bundesstaatsprinzip',
      'Gleichheitsprinzip',
      'Rechtsstaatsprinzip',
    ],
    correct: [3],
  },
  {
    id: 2,
    type: 'multi',
    topic: 'Staatsrecht – Bundeswehr-Legitimation',
    q: 'Welcher Artikel des Grundgesetzes legitimiert den Einsatz der Bundeswehr?',
    options: ['Art. 20 GG', 'Art. 4 GG', 'Art. 87a GG'],
    correct: [2],
  },
  {
    id: 3,
    type: 'multi',
    topic: 'Staatsrecht – FDGO',
    q: 'Welche Inhalte des Grundgesetzes (Staatsstrukturprinzipien) umfasst die FDGO nach dem Bundesverfassungsgericht?',
    options: [
      'Rechtsstaatsprinzip',
      'Republikprinzip',
      'Demokratieprinzip',
      'Bundesstaatsprinzip',
      'Sozialstaatsprinzip',
      'Menschenwürde',
    ],
    correct: [0, 1, 2, 3, 4],
  },
  {
    id: 5,
    type: 'multi',
    topic: 'Befehlsrecht – Fall StUffz Pietsch / Flieger Siebert',
    q:
      'Flieger Siebert ist mehrmals durch einen unordentlichen Spind aufgefallen. Sein Gruppenführer, Stabsunteroffizier Pietsch, befiehlt ihm deshalb, sich ab sofort als „Flieger Schweinchen" zu melden.\n\nKreuzen Sie die richtige(n) Antwort(en) an.',
    options: [
      'Der Befehl ist aufgrund eines Verstoßes gegen ein Gesetz rechtswidrig.',
      'Der Befehl ist rechtmäßig, da kein Rechtfertigungsgrund vorliegt.',
      'Der Befehl ist unverbindlich, da er die Menschenwürde des Flieger Siebert verletzt.',
      'Der Befehl ist verbindlich, da kein Unverbindlichkeitsgrund vorliegt.',
      'Der Befehl ist unverbindlich, da er unzumutbar ist.',
      'Der Befehl muss nicht befolgt werden.',
      'Der Befehl darf nicht befolgt werden.',
      'Der Befehl muss befolgt werden.',
    ],
    correct: [0, 2, 4, 5],
  },
  {
    id: 6,
    type: 'multi',
    topic: 'SG – Dienstvergehen Fw Schober',
    q:
      'Fw Schober (Zugführer, außer Dienst in Kneipe) macht sich lautstark über Flieger Heil lustig, bezeichnet ihn als „Niete" und „Schande für die Bundeswehr", und lässt Flieger Heil anschließend betrunken (1,5 ‰) mit dem Auto fahren.\n\nHat Fw Schober ein oder mehrere Dienstvergehen begangen? Kreuzen Sie die richtige(n) Antwort(en) an.',
    options: [
      'Er hat gegen § 7, 1. Halbsatz SG (Pflicht zum treuen Dienen) verstoßen, indem er den Flieger Heil u.a. als „Niete" bezeichnet hat bzw. beging er eine Straftat, was eine Kernpflichtverletzung (Loyalitätspflicht) ist.',
      'Er hat nicht gegen § 7, 1. Halbsatz SG (Pflicht zum treuen Dienen) verstoßen, da keine Kernpflichtverletzung vorliegt.',
      'Er hat gegen § 10 Abs. 1 SG (Pflichten des Vorgesetzten) verstoßen, da er in Haltung und Pflichterfüllung kein Beispiel gegeben hat.',
      'Er hat gegen § 10 Abs. 2 SG (Dienstaufsichtspflicht) verstoßen, indem er den Flieger Heil nicht von seiner Trunkenheitsfahrt nach § 316 StGB abgehalten hat.',
      'Er hat nicht gegen § 10 Abs. 2 SG (Dienstaufsichtspflicht) verstoßen, da er nicht im Dienst gewesen ist.',
      'Er hat gegen § 10 Abs. 3 SG (Fürsorgepflicht) verstoßen, indem er den Flieger Heil durch die Bezeichnung „Niete" in dessen Ehre verletzt hat.',
      'Er hat gegen § 10 Abs. 3 SG (Fürsorgepflicht) verstoßen, indem er den Flieger Heil nicht von seiner Trunkenheitsfahrt nach § 316 StGB abgehalten hat.',
      'Er hat nicht gegen § 10 Abs. 3 SG (Fürsorgepflicht) verstoßen, da er außer Dienst dem Flieger Heil nicht vorgesetzt ist.',
      'Er hat gegen § 10 Abs. 6 SG (Pflicht zur Zurückhaltung) verstoßen, indem er den Flieger Heil in Anwesenheit seiner Untergebenen als „Niete" bezeichnete.',
      'Er hat nicht gegen § 10 Abs. 6 SG (Pflicht zur Zurückhaltung bei Äußerungen) verstoßen, da es sich hierbei um eine private Feier handelte.',
      'Er hat gegen § 12 S. 2 SG (Kameradschaftspflicht) verstoßen, indem er den Flieger Heil als „Niete" bezeichnete. Damit hat er ihn in dessen Ehre verletzt.',
      'Er hat gegen § 17 Abs. 2 S. 3, 2. Alternative SG (außerdienstliche Wohlverhaltenspflicht) verstoßen, da er durch sein Verhalten nicht der Achtung und dem Vertrauen gerecht geworden ist, die sein Dienst als Soldat erfordert.',
      'Er hat gegen § 17 Abs. 2 S. 3, 1. Alternative SG (außerdienstliche Wohlverhaltenspflicht) verstoßen, indem er durch sein Verhalten in der Öffentlichkeit das Ansehen der Bundeswehr beeinträchtigt hat.',
      'Er handelte vorsätzlich, also mit Wissen und Wollen.',
      'Er handelte fahrlässig, da er die im Verkehr erforderliche Sorgfalt außer Acht ließ.',
      'Er handelte rechtswidrig, da keine Rechtfertigungsgründe vorlagen.',
      'Er handelte nicht schuldhaft, da ein Schuldausschlussgrund gemäß § 20 StGB vorlag.',
      'Er hat mehrere Dienstpflichtverletzungen begangen.',
      'Er hat mehrere Dienstvergehen gemäß § 23 Abs. 1 SG begangen.',
      'Er hat kein Dienstvergehen gemäß § 23 Abs. 1 SG begangen.',
    ],
    correct: [0, 2, 3, 5, 6, 8, 10, 11, 13, 14, 15, 17],
  },
  {
    id: 7,
    type: 'multi',
    topic: 'StGB – Strafbarkeit Flieger Heil',
    q:
      'Hat sich der Flieger Heil (1,5 ‰, Trunkenheitsfahrt, Schaden 2.500 € am Dienstfahrzeug, keine Verletzten) durch sein Verhalten strafbar gemacht?\n\nKreuzen Sie die richtige(n) Antwort(en) an.',
    options: [
      'Er hat sich nach § 303 Abs. 1 StGB strafbar gemacht.',
      'Er hat sich nach § 315 b StGB strafbar gemacht.',
      'Er hat sich nach § 316 StGB strafbar gemacht.',
      'Er hat sich nach § 323a StGB strafbar gemacht.',
      'Er hat sich nach § 20 Abs. 1 Nr. 1 WStG strafbar gemacht.',
      'Er hat sich nach § 25 Abs. 1 WStG strafbar gemacht.',
    ],
    correct: [2],
  },
  {
    id: 8,
    type: 'text',
    topic: 'WDO – Legalitätsprinzip (Fw Schober)',
    q:
      'Sie sind der KpChef 3./LwAusbBtl und haben persönlich ein gutes Verhältnis zu Fw Schober. Nun fragen Sie sich, ob Sie verpflichtet sind, disziplinare Ermittlungen gegen ihn aufzunehmen.\n\nBeantworten Sie die Frage unter Nennung des einschlägigen Paragraphen.',
    fields: [
      { label: 'Verpflichtet / nicht verpflichtet?', answer: 'verpflichtet' },
      { label: 'Rechtsgrundlage', answer: '§ 32 Abs. 1 WDO' },
      { label: 'Bezeichnung des Grundsatzes', answer: 'Legalitätsprinzip' },
    ],
  },
  {
    id: 9,
    type: 'text',
    topic: 'WDO – Verhängungsfrist (Fw Schober, Tat 19.07)',
    q:
      'Ihre Ermittlungen sind nun abgeschlossen. Bis wann müssten Sie spätestens eine Disziplinarmaßnahme gegen Fw Schober verhängen?\n\nBeantworten Sie die Frage unter Nennung der einschlägigen Norm. (Tatdatum: 19.07.)',
    fields: [
      { label: 'Spätestes Datum', answer: '18.01' },
      { label: 'Uhrzeit', answer: '24:00' },
      { label: 'Norm', answer: '§ 17 Abs. 2 WDO' },
    ],
  },
  {
    id: 10,
    type: 'text',
    topic: 'WDO – Früheste Vollstreckung Ausgangsbeschränkung (Flieger Heil, Verhängung 25.07)',
    q:
      'Da auch Flieger Heil ein Dienstvergehen begangen hat, verhängen Sie gegen ihn am 25.07 eine Ausgangsbeschränkung von sieben Tagen. Wann dürfen Sie diese Disziplinarmaßnahme frühestens vollstrecken?\n\nBeantworten Sie die Frage unter Nennung der einschlägigen Normen.',
    fields: [
      { label: 'Frühestes Datum', answer: '27.07' },
      { label: 'Uhrzeit', answer: '00:00' },
      { label: 'Normen', answer: '§ 47 Abs. 1, 52 Abs. 2 WDO' },
    ],
  },
  {
    id: 11,
    type: 'text',
    topic: 'WBO – Beschwerdefrist Flieger Heil (Verhängung 25.07)',
    q:
      'Flieger Heil möchte sich gegen die Verhängung der Ausgangsbeschränkung beschweren. Wann ist der frühestmögliche und der späteste Zeitpunkt, zu dem die Beschwerde eingegangen sein muss?\n\nBeantworten Sie die Frage unter Nennung der einschlägigen Norm.',
    fields: [
      { label: 'Frühestens ab (Datum)', answer: '26.07' },
      { label: 'Frühestens ab (Uhrzeit)', answer: '06:00' },
      { label: 'Spätestens bis (Datum)', answer: '25.08' },
      { label: 'Spätestens bis (Uhrzeit)', answer: '24:00' },
      { label: 'Norm', answer: '§ 6 Abs. 1 WBO' },
    ],
  },
  {
    id: 12,
    type: 'text',
    topic: 'WDO – Vollstreckungsverjährung (Flieger Heil, Rücknahme 20.08)',
    q:
      'Flieger Heil zieht seine fristgerecht eingelegte Beschwerde am 20.08 wieder zurück. Bis wann muss die gegen ihn verhängte Ausgangsbeschränkung spätestens vollstreckt sein?\n\nBeantworten Sie die Frage unter Nennung der einschlägigen Norm.',
    fields: [
      { label: 'Vollstreckung spätestens bis (Datum)', answer: '25.02' },
      { label: 'Uhrzeit', answer: '24:00' },
      { label: 'Norm', answer: '§ 57 WDO' },
    ],
  },
  {
    id: 13,
    type: 'multi',
    topic: 'WBO/WDO – Beschwerdeart Flieger Heil',
    q:
      'Um welche Beschwerdeart würde es sich bei der Beschwerde des Flieger Heil (gegen die verhängte Ausgangsbeschränkung des KpChef) handeln und wer wäre für die Entscheidung zuständig?\n\nKreuzen Sie die richtige(n) Antwort(en) an.',
    options: [
      'Truppendienstliche Beschwerde, über die das Truppendienstgericht zu entscheiden hat (§ 42 Nr. 4 WDO).',
      'Disziplinarbeschwerde, über die das Truppendienstgericht zu entscheiden hat (§ 42 Nr. 5 WDO).',
      'Truppendienstliche Beschwerde, über die der nächste Disziplinarvorgesetzte des verhängenden Kompaniechefs, d.h. der Bataillonskommandeur zu entscheiden hat (§ 9 Abs. 1 WBO).',
      'Disziplinarbeschwerde, über die der nächste Disziplinarvorgesetzte des verhängenden Kompaniechefs, d.h. der Bataillonskommandeur zu entscheiden hat (§ 42 Nr. 3 WDO).',
    ],
    correct: [3],
  },
  {
    id: 14,
    type: 'multi',
    topic: 'SG – Dienstvergehen OGefr OA Müller',
    q:
      'OGefr OA Müller erscheint am 17.03 nicht zum Dienst, wird am 20.03 mit Flugticket nach Sydney angehalten. Er weigert sich, dem Befehl des Feldjägerstreifenführers OFw Schulze zu folgen, bezeichnet ihn als „Folterknecht" und tritt ihm gegen das Schienbein.\n\nHat OGefr OA Müller durch sein Verhalten ein Dienstvergehen begangen? Kreuzen Sie die richtige(n) Antwort(en) an.',
    options: [
      'Er hat gegen § 7, 1. Halbsatz SG (Pflicht zum treuen Dienen) verstoßen, indem er am 17.03. entgegen des Dienstplans nicht um 07:00 Uhr zum Dienst erschienen ist, was eine Kernpflichtverletzung darstellt.',
      'Er hat gegen § 11 Abs. 1 SG (Gehorsamspflicht) verstoßen, indem er am 17.03. entgegen des Dienstplans nicht um 07:00 Uhr zum Dienst erschienen ist.',
      'Er hat nicht gegen § 11 Abs. 1 SG (Gehorsamspflicht) verstoßen, da der Dienstplan nur durch ein Aufhängen nicht zum verbindlichen Befehl wird.',
      'Er hat gegen § 12 S. 2 SG (Kameradschaftspflicht) verstoßen, da er durch die Bezeichnung des OFw Schulze als „Folterknecht" diesen in dessen Ehre verletzt hat.',
      'Er hat gegen § 7, 1. Halbsatz SG (Pflicht zum treuen Dienen) verstoßen, indem er den OFw Schulze als „Folterknecht" bezeichnet hat und somit eine Straftat mit dienstlichem Bezug begangen hat.',
      'Er hat nicht gegen § 7, 1. Halbsatz SG (Pflicht zum treuen Dienen) verstoßen, da keine Kernpflichtverletzung vorliegt.',
      'Er hat gegen § 12 S. 2 SG (Kameradschaftspflicht) verstoßen, indem er den OFw Schulze gegen das Schienbein getreten hat, wodurch er ihn in dessen Recht auf körperliche Unversehrtheit beeinträchtigte.',
      'Er hat gegen § 13 Abs. 1 SG (Wahrheitspflicht) verstoßen, da er mit der Äußerung der OFw Schulze sei ein „Folterknecht" in dienstlichen Angelegenheiten die Unwahrheit gesagt hat.',
      'Er hat nicht gegen § 12 S. 2 SG (Kameradschaftspflicht) verstoßen, da der OFw Schulze als Feldjägerstreifenführer in diesem Moment kein Kamerad ist.',
      'Er hat gegen § 17 Abs. 1 SG (Achtung der dienstlichen Stellung des Vorgesetzten) verstoßen, indem er den OFw Schulze als „Folterknecht" bezeichnet und ihn tritt.',
      'Er hat nicht gegen § 17 Abs. 1 SG (Achtung der dienstlichen Stellung eines Vorgesetzten) verstoßen, da ihm OFw Schulze außerhalb einer umschlossenen militärischen Anlage nicht vorgesetzt ist.',
      'Er hat gegen § 17 Abs. 2 S. 3, 2. Alternative SG (außerdienstliche Wohlverhaltenspflicht) verstoßen, indem er OFw Schulze getreten hat.',
      'Er handelte fahrlässig, da er die im Verkehr erforderliche Sorgfalt außer Acht lässt.',
      'Er handelte rechtswidrig, da keine Rechtfertigungsgründe vorliegen.',
      'Er handelt hier hinsichtlich des Fußtritts gegenüber OFw Schulze gemäß § 35 StGB entschuldigt.',
      'Er hat kein Dienstvergehen gemäß § 23 Abs. 1 SG begangen.',
      'Er hat gegen mehrere soldatische Pflichten verstoßen.',
      'Er hat gegen § 7, 1. Halbsatz SG (Pflicht zum treuen Dienen) verstoßen, indem er mit dem Fußtritt gegen OFw Schulze seine Vermögenswahrnehmungspflicht verletzt hat.',
    ],
    correct: [0, 1, 3, 4, 6, 9, 11, 13, 16],
  },
  {
    id: 15,
    type: 'multi',
    topic: 'WDO – Belehrung vor Vernehmung (OGefr OA Müller)',
    q:
      'Mit welchem Inhalt muss OGefr OA Müller vor seiner Vernehmung belehrt werden?\n\nKreuzen Sie die richtige(n) Antwort(en) an.',
    options: [
      'OGefr OA Müller muss aussagen, wenn er weder sich noch nahe Angehörige mit seiner Aussage belasten würde.',
      'OGefr OA Müller unterliegt im Fall seiner Aussage nicht der Wahrheitspflicht.',
      'OGefr OA Müller muss aussagen, außer er würde sich selbst belasten.',
      'OGefr OA Müller steht es frei, sich zur Sache zu äußern oder nicht auszusagen.',
      'OGefr OA Müller muss in dienstlichen Angelegenheiten die Wahrheit sagen, wenn er aussagt.',
      'OGefr OA Müller muss nicht aussagen, wenn er sich selbst oder einen nahen Angehörigen mit seiner Aussage belasten würde. Ansonsten besteht eine Aussagepflicht.',
    ],
    correct: [3, 4],
  },
  {
    id: 16,
    type: 'multi',
    topic: 'WStG – Strafbarkeit OGefr OA Müller',
    q: 'Hat sich OGefr OA Müller gemäß WStG strafbar gemacht?\n\nKreuzen Sie die richtige(n) Antwort(en) an.',
    options: [
      'Er hat sich nach § 15 Abs. 1 WStG strafbar gemacht.',
      'Er hat sich nach § 16 Abs. 1 WStG strafbar gemacht.',
      'Er hat sich nach § 19 Abs. 1 WStG strafbar gemacht.',
      'Er hat sich nach § 20 Abs. 1 Nr. 1 WStG strafbar gemacht.',
      'Er hat sich nach § 20 Abs. 1 Nr. 2 WStG strafbar gemacht.',
      'Er hat sich nach § 25 Abs. 1 WStG strafbar gemacht.',
      'Er hat sich nach § 18 Abs. 1 WStG strafbar gemacht.',
    ],
    correct: [1, 3, 4, 5],
  },
  {
    id: 17,
    type: 'text',
    topic: 'WDO – Zuständigkeit Inspektionschef (OGefr OA Müller)',
    q:
      'Aus welcher Vorschrift ergibt sich die Zuständigkeit des Inspektionschefs für die Ausübung der Disziplinarbefugnis gegenüber OGefr OA Müller?\n\nBeantworten Sie die Frage.',
    fields: [{ label: 'Norm', answer: '§ 29 Abs. 1 WDO' }],
  },
  {
    id: 18,
    type: 'multi',
    topic: 'WDO/WBO – Rechtsbehelf nach Beschwerde-Zurückweisung (OGefr OA Müller)',
    q:
      'Der Inspektionschef verhängt gegen OGefr OA Müller eine 7-tägige Ausgangsbeschränkung. Die Beschwerde des OGefr OA Müller wird zurückgewiesen. Welchen Rechtsbehelf kann er jetzt einlegen?\n\nKreuzen Sie die richtige(n) Antwort(en) an.',
    options: [
      'die weitere Beschwerde beim Truppendienstgericht (§ 42 Nr. 4 WDO).',
      'die weitere Beschwerde beim Lehrgruppenkommandeur (§ 16 Abs. 1 WBO)',
      'der Antrag auf Entscheidung beim Truppendienstgericht (§ 17 Abs. 1 WBO)',
      'die weitere Unzulässigkeitsbeschwerde beim Schulkommandeur (§ 16 Abs. 2 WBO)',
    ],
    correct: [0],
  },
  {
    id: 19,
    type: 'multi',
    topic: 'Befehlsrecht – Allgemeine Aussagen',
    q: 'Welche der nachfolgend aufgeführten Aussagen zum Befehlsrecht trifft/treffen zu?',
    options: [
      'Ein Befehl, der rechtswidrig und verbindlich ist, braucht nicht befolgt zu werden.',
      'Verstößt ein Befehl gegen Gesetze, darf er nicht ausgeführt werden.',
      'Ein rechtmäßiger Befehl ist auch immer verbindlich.',
      'Unverbindliche Befehle sind rechtswidrig und müssen nicht oder dürfen nicht befolgt werden.',
      'Befehle, die nicht ausgeführt werden müssen, sind rechtswidrig und unverbindlich.',
    ],
    correct: [2, 3, 4],
  },
  {
    id: 20,
    type: 'multi',
    topic: 'WDO – Erzieherische Maßnahmen / Vorgesetztenrechte',
    q: 'Welche der nachfolgend aufgeführten Aussagen treffen zu?',
    options: [
      'Ein Gruppenführer darf einen unwilligen Soldaten seiner Gruppe zurechtweisen.',
      'Ein Zugführer darf einem besonders motivierten Soldaten seines Zuges vorzeitig Dienstschluss erteilen.',
      'Ein Staffelchef darf nur besondere Erzieherische Maßnahmen verhängen und keine anderen.',
      'Ein KpChef darf, auch wenn er eine Disziplinarmaßnahme für geboten hält, als mildere Maßnahme eine Erzieherische Maßnahme wegen eines Dienstvergehens verhängen.',
      'Eine Erzieherische Maßnahme muss spätestens nach 6 Monaten verhängt worden sein.',
      'Es ist keine zulässige Erzieherische Maßnahme, einen unwilligen Soldaten zur Erziehung Backsteine mit dessen Namen herumtragen zu lassen.',
      'Gegen eine Erzieherische Maßnahme ist eine truppendienstliche Beschwerde statthaft.',
    ],
    correct: [0, 4, 5, 6],
  },
  {
    id: 21,
    type: 'multi',
    topic: 'VorgV – Vorgesetztenverhältnisse OLt Fuchs / Fw Peters',
    q:
      'OLt Fuchs ist Zugführer I. Zug, 2. Kompanie im Luftwaffenausbildungsbataillon und in Zweitfunktion der Jugendoffizier des Bataillons.
In dieser Funktion ist er gemäß Bataillonsbefehl vom 20.03. verantwortlich für die Betreuung einer Schulklasse, die den Verband am 01.04. besucht. Dabei unterstützt ihn Fw Peters, Gruppenführer 1. Gruppe, I. Zug, 2. Kompanie im Luftwaffenausbildungsbataillon bei der Betreuung der Schulklasse. Im Verlauf einer Führung im Kasernenbereich trifft Fw Peters seinen stellvertretenden Gruppenführer Uffz Lietke, der entgegen des Befehls des Bataillonskommandeurs keine Kopfbedeckung trägt und befiehlt ihm, umgehend seine Kopfbedeckung aufzusetzen.
',
    options: [
      '§ 4 Abs. 3 VorgV',
      '§ 2 VorgV',
      '§ 4 Abs. 1 S. 1 Nr. 1 VorgV',
      '§ 1 VorgV',
      '§ 6 VorgV',
      '§ 4 Abs. 2 in Verbindung mit § 4 Abs. 1 S. 1 Nr. 1 VorgV',
    ],
    correct: [0, 2, 3],
  },
  {
    id: 22,
    type: 'multi',
    topic: 'VorgV – Vorgesetztenverhältnisse Hptm Boll (Gottesdienst)',
    q:
      'Die Kompaniechefin, Hptm Boll, gibt an alle Angehörigen ihrer Einheit (Mannschaften und Unteroffiziere) beim morgendlichen Antreten den Befehl: Teilnahme am ökumenischen Standortgottesdienst während des Dienstes.\n\nPrüfen Sie, nach welchen Vorschriften ein Vorgesetztenverhältnis gegeben ist.',
    options: [
      '§ 3 VorgV',
      '§ 1 VorgV',
      '§ 4 Abs. 3 VorgV',
      '§ 5 VorgV',
      '§ 4 Abs. 2 in Verbindung mit § 4 Abs. 1 S. 1 Nr. 1 VorgV',
      '§ 4 Abs. 1 S. 1 Nr. 1 VorgV',
    ],
    correct: [1, 2, 5],
  },
  {
    id: 23,
    type: 'multi',
    topic: 'WStG / SG – StUffz S (Kantine)',
    q:
      'StUffz S pöbelt im betrunkenen Zustand (1,8 ‰) nach Dienst in einer Kantine in der K-Kaserne die zivile Bedienung u.a. mit den Worten an: „Du Schlampe, Dich leg ich auch noch flach."\n\nKreuzen Sie die richtige(n) Aussage(n) an.',
    options: [
      'Es begeht eine Straftat nach § 31 WStG, weil er die Bedienung erniedrigend behandelt.',
      'Es begeht eine Straftat nach § 31 WStG und ein Dienstvergehen nach § 23 Abs. 1 SG, weil er auch gegen § 17 Abs. 2 S. 1 SG verstößt.',
      'Es begeht keine Wehrstraftat, aber ein Dienstvergehen.',
      'Es begeht keine Wehrstraftat nach § 31 WStG und kein Dienstvergehen nach § 23 Abs. 1 SG, weil er schuldunfähig gemäß § 20 StGB ist.',
      'Es begeht keine Wehrstraftat und kein Dienstvergehen.',
    ],
    correct: [2],
  },
  {
    id: 24,
    type: 'multi',
    topic: 'Allgemeines Straf- und Disziplinarrecht – Grundsätze',
    q:
      'Welche Aussage(n) hinsichtlich allgemeiner strafrechtlicher und disziplinarrechtlicher Grundsätze ist/sind richtig?\n\nKreuzen Sie die richtige(n) Aussage(n) an.',
    options: [
      'Das Strafverfahren und das Disziplinarverfahren verfolgen unterschiedliche Zwecke.',
      'Der Disziplinarvorgesetzte geht gegen Soldatinnen und Soldaten vor, indem er diese bestraft.',
      'Der Disziplinarvorgesetzte ahndet Dienstpflichtverletzungen.',
      'Das Disziplinarverfahren dient der Erziehung.',
      'Die Freiheitsstrafe im Sinne des StGB, die ein Strafrichter aussprechen darf, verfolgt denselben Zweck wie der Disziplinararrest, den der Disziplinarvorgesetzte verhängen kann.',
      'Die fahrlässige Verwirklichung eines Straftatbestandes ist immer unter Strafe gestellt.',
      'Ein Dienstvergehen ist der rechtswidrige und schuldhafte Verstoß gegen soldatische Pflichten und das Strafgesetzbuch.',
      'Der Versuch eines Vergehens im Sinne des StGB ist immer strafbar, auch wenn das jeweilige Strafgesetz es nicht ausdrücklich anordnet.',
    ],
    correct: [0, 2, 3],
  },
  {
    id: 25,
    type: 'multi',
    topic: 'WDO – Verbindung Disziplinarmaßnahme / Erzieherische Maßnahme (Uffz Meier)',
    q:
      'Unteroffizier Meier erscheint zweimal grundlos zu spät zum Dienst. Die Staffelchefin verhängt gegen ihn eine Disziplinarbuße in Höhe von 200 Euro, deren Vollstreckung sie zur Bewährung aussetzt.\n\nKreuzen Sie die richtige Aussage an.',
    options: [
      'Die einfache Disziplinarmaßnahme kann hier mit einer schriftlichen Ausarbeitung zum Thema „Dienstleistungspflicht" verbunden werden.',
      'Die Erteilung einer einfachen Disziplinarmaßnahme neben einer erzieherischen Maßnahme darf grundsätzlich niemals erfolgen.',
      'Die Staffelchefin kann neben der Verhängung der einfachen Disziplinarmaßnahme zusätzlich den Soldaten auch noch zum Wachdienst einteilen (Zusatzdienst als Wiederholungszusatzdienst).',
      'Die Staffelchefin kann neben der Verhängung der einfachen Disziplinarmaßnahme zusätzlich eine schriftliche Ausarbeitung für 2 Stunden nach Dienstende aussprechen.',
    ],
    correct: [0],
  },
  // ── Zeitablauf Übungsfälle ──────────────────────────────
  {
    id: 101,
    type: 'text',
    topic: 'Zeitablauf Fall 1 – Tat: 04.05',
    q: 'Die Soldatin begeht am 04.05.20xx ein Dienstvergehen. Schlussgehör (§ 32 Abs. 5 WDO) am 31.05.20xx.',
    fields: [
      { label: 'a) Früheste Verhängung (§ 37 Abs. 1 WDO) – Datum u. Uhrzeit', answer: '01.06.20xx, 06:00 Uhr' },
      { label: 'b) Früheste Vollstreckung (§ 47 Abs. 1 WDO) – Datum u. Uhrzeit', answer: '02.06.20xx, 13:00 Uhr' },
      { label: 'c) Späteste Verhängung (§ 17 Abs. 2 WDO) – Datum u. Uhrzeit', answer: '03.11.20xx, 24:00 Uhr' },
      { label: 'd) Verhängungsverbot ab – Datum u. Uhrzeit', answer: '04.11.20xx, 00:00 Uhr' },
      { label: 'e) Früheste Beschwerde (Verhängung 01.06.) – Datum u. Uhrzeit', answer: '02.06.20xx, 06:00 Uhr' },
      { label: 'f) Späteste Beschwerde (Verhängung 01.06.xx) – Datum u. Uhrzeit', answer: '01.07.20xx, 24:00 Uhr' },
      { label: 'g) Unanfechtbar ab – Datum u. Uhrzeit', answer: '02.07.20xx, 00:00 Uhr' },
      { label: 'h) Beschwerdeart bei Disziplinarbuße', answer: 'Disziplinarbeschwerde § 42 WDO' },
      { label: 'i) Späteste Vollstreckung (§ 57 Abs. 1 WDO) – Datum u. Uhrzeit', answer: '01.01.20xx, 24:00 Uhr' },
      { label: 'j) Vollstreckung unzulässig ab – Datum u. Uhrzeit', answer: '02.01.20xx, 00:00 Uhr' },
    ],
  },
  {
    id: 102,
    type: 'text',
    topic: 'Zeitablauf Fall 2 – Tat: 12.08.',
    q: 'Der Soldat begeht am 12.08.20xx ein Dienstvergehen. Schlussgehör am 17.08.20xx.',
    fields: [
      { label: 'a) Früheste Verhängung – Datum u. Uhrzeit', answer: '18.08.20xx, 06:00 Uhr' },
      { label: 'b) Früheste Vollstreckung – Datum u. Uhrzeit', answer: '19.08.20xx, 13:00 Uhr' },
      { label: 'c) Späteste Verhängung – Datum u. Uhrzeit', answer: '11.02.20xx, 24:00 Uhr' },
      { label: 'd) Verhängungsverbot ab – Datum u. Uhrzeit', answer: '12.02.20xx, 00:00 Uhr' },
      { label: 'e) Früheste Beschwerde (Verhängung 18.08.) – Datum u. Uhrzeit', answer: '19.08.20xx, 06:00 Uhr' },
      { label: 'f) Späteste Beschwerde (Verhängung 18.08.xx) – Datum u. Uhrzeit', answer: '18.09.20xx, 24:00 Uhr' },
      { label: 'g) Unanfechtbar ab – Datum u. Uhrzeit', answer: '19.09.20xx, 00:00 Uhr' },
      { label: 'h) Beschwerdeart bei Disziplinararrest', answer: 'Disziplinarbeschwerde § 42 WDO' },
      { label: 'i) Späteste Vollstreckung (§ 57 Abs. 1 WDO) – Datum u. Uhrzeit', answer: '18.03.20xx, 24:00 Uhr' },
      { label: 'j) Vollstreckung unzulässig ab – Datum u. Uhrzeit', answer: '19.03.20xx, 00:00 Uhr' },
    ],
  },
  {
    id: 103,
    type: 'text',
    topic: 'Zeitablauf Fall 3 – Tat: 02.11.',
    q: 'Der Soldat begeht am 02.11.20xx ein Dienstvergehen. Schlussgehör am 29.11.20xx.',
    fields: [
      { label: 'a) Früheste Verhängung – Datum u. Uhrzeit', answer: '30.11.20xx, 06:00 Uhr' },
      { label: 'b) Früheste Vollstreckung – Datum u. Uhrzeit', answer: '01.12.20xx, 13:00 Uhr' },
      { label: 'c) Späteste Verhängung – Datum u. Uhrzeit', answer: '01.05.20xx, 24:00 Uhr' },
      { label: 'd) Verhängungsverbot ab – Datum u. Uhrzeit', answer: '02.05.20xx, 00:00 Uhr' },
      { label: 'e) Früheste Beschwerde (Verhängung 30.11.) – Datum u. Uhrzeit', answer: '01.12.20xx, 06:00 Uhr' },
      { label: 'f) Späteste Beschwerde (Verhängung 30.11.xx) – Datum u. Uhrzeit', answer: '30.12.20xx, 24:00 Uhr' },
      { label: 'g) Unanfechtbar ab – Datum u. Uhrzeit', answer: '31.12.20xx, 00:00 Uhr' },
      { label: 'h) Beschwerdeart bei strengem Verweis', answer: 'Disziplinarbeschwerde § 42 WDO' },
      { label: 'i) Späteste Vollstreckung (§ 57 Abs. 1 WDO) – Datum u. Uhrzeit', answer: '30.06.20xx, 24:00 Uhr' },
      { label: 'j) Vollstreckung unzulässig ab – Datum u. Uhrzeit', answer: '01.07.20xx, 00:00 Uhr' },
    ],
  },
]

export default QUESTIONS
